Repository Miksus/red-mail, pull requests merged in 2022-01, with the labels that each got.

#11 ENH: Support non TLS connection
  docs/tutorials/client.rst
  docs/tutorials/index.rst
  redmail/email/sender.py
  redmail/test/email/test_send.py
Labels: enhancement

#18 docs: Fixed typo
  docs/tutorials/example.rst
  redmail/email/sender.py
Labels: documentation

#16 fix: support non-PNG embedded images as dict
  redmail/email/body.py
  redmail/test/email/test_inline_media.py
Labels: bug

#24 23 fix contenttype attachment
  redmail/email/attachment.py
  redmail/test/email/test_attachments.py
Labels: bug

#22 DOCS: add address aliases
  docs/tutorials/sending.rst
Labels: documentation

#21 ENH: Outlook sender
  docs/index.rst
  docs/tutorials/config.rst
  docs/tutorials/getting_started.rst
  redmail/__init__.py
  redmail/email/__init__.py
Labels: documentation, enhancement

#25 ENH: Logging handlers
  ci/file.html
  ci/test_send.py
  docs/conf.py
  docs/extensions/index.rst
  docs/extensions/logging.rst
  docs/index.rst
  docs/references.rst
  docs/tutorials/client.rst
  redmail/__init__.py
  redmail/email/sender.py
  redmail/log.py
  redmail/test/log/__init__.py
  redmail/test/log/conftest.py
  redmail/test/log/test_construct.py
  redmail/test/log/test_handler.py
  redmail/test/log/test_handler_multi.py
  tox.ini
Labels: enhancement

#28 add: support for sending multiple emails
  docs/tutorials/sending.rst
  redmail/email/sender.py
  redmail/test/email/test_send.py
Labels: enhancement

#29 DOCS: add flask-redmail
  docs/extensions/flask.rst
  docs/extensions/index.rst
  docs/extensions/logging.rst
  docs/index.rst
Labels: documentation
